name: Create Archive
on:
  push:
    branches:
      main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
 
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: '${{ steps.date.outputs.date }}ZZZZZZKorlang.z2f'
        

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ steps.date.outputs.date }}ZZZZZZKorlang.z2f"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ver-${{ steps.date.outputs.date }}
        name: ZT2 Korean Patch ${{ steps.date.outputs.date }}
